server:
  port: 9000

spring:
  application:
    name: service-product
  cloud:
    sentinel:
      transport:
        # 控制台地址
        dashboard: localhost:8080
      # 立即加载服务
      eager: true
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
